name: Auto-Assign Issues & PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign to Millie
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: "Millie-Jackson"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
