name: Update Project Board

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, merged]

jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - name: Move Issue to "In Progress"
        if: github.event.action == 'opened'
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/Millie-Jackson/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-name: "In Progress"

      - name: Move Issue to "Done" on Close
        if: github.event.action == 'closed'
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/Millie-Jackson/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-name: "Done"
